name: Terraform infra service catalog
 
on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform-infra-service-catalog:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::664418994073:role/github-oidc-service-catalog
        aws-region: ap-south-1
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
 
    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Validate
      run: terraform validate
 
    - name: Terraform Plan
      run: terraform plan
 
    - name: Terraform Apply
      run: terraform apply -auto-approve
